apiVersion: v1
kind: Service
metadata:
  name: verification-runner
  namespace: contract-testing
  labels:
    app: verification-runner
spec:
  type: ClusterIP
  selector:
    app: verification-runner
  ports:
    - port: 4002
      targetPort: 4002
      protocol: TCP
